name: libspm-CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
    TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  # add test matrix to run tests on ubuntu-22.04 and macos-12 using g++12
  run-libspm-unit-tests:
    name: Run libspm unit tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-14]
        compiler: [gcc-13]
        build_type: [Release]
        test_suite: ["test/api/libspm"]
        cxx_flags: ["-fdiagnostics-color -ftemplate-backtrace-limit=0 -fconcepts-diagnostics-depth=2"]
        include:
          - os: macos-14
            threads: 3
          - os: ubuntu-22.04
            threads: 2
    uses: ./.github/workflows/base_ci.yml
    with:
      os: ${{ matrix.os }}
      compiler: ${{ matrix.compiler }}
      build_type: ${{ matrix.build_type }}
      test_suite: ${{ matrix.test_suite }}
      cxx_flags: ${{ matrix.cxx_flags }}
      threads: ${{ matrix.threads }}
